<?php
use Modules\Kernel\Session;
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><?= $this->title ?? SITE_NAME  ?></title>
	<link href="/public/favicon.ico" rel="icon">

	<!-- Site stylesheets -->
	<link href="/public/global.css" rel="stylesheet">
	<?php if(isset($this->styleSheet)): ?>
	<link href="/public/<?= $this->styleSheet ?>" rel="stylesheet">
	<?php endif ?>
	<!-- Site scripts -->
	<script src="/public/main.js" type="module"></script>
	<?php if(isset($this->script)): ?>
	<script src="/public/<?= $this->script ?>" type="module"></script>
	<?php endif ?>
</head>
<body>
	<header></header>
	<main><?php parent::render(); ?></main>
	<footer></footer>
</body>
</html>
